### ISSUE TITLE
Using with IFC1211 and ADC3117

### ISSUE THREAD

**Issue by gohierf** [paulscherrerinstitute/tosca#1]
Hello,
We intend to use your driver with a IFC1211 and an ADC3117.
Have you already tried it in this configuration ?
From the docs I assume it should work in the following situations :
IFC1211 and ADC3117
IFC1210 and ADC3117
IFC1210 and ADC3111
Which of these have you already tried ?
Anything we should expect to go wrong ?
Thanks,
Francis

**Comment by dirk-zimoch** [comment]
I have never tried any ADC. Everything about ADCs the docs is second hand from other docs.

**Comment by dirk-zimoch** [comment]
My colleague who has more experience with the IOxOS ADCs expects no problems, though he also has not tried the ADC3117. Also we don't use IFC1211 in production, only IFC1210. But the interface is so similar that it should work.

**Comment by gohierf** [comment]
Alright thanks for the updates, I will let you know how we are doing on this topic.
